### ISSUE TITLE
example of this library for vuejs

### ISSUE THREAD

**Issue by cax111** [spurushottam13/bifrost-cross#2]
hei... can you provide an example of this library for vuejs ? cause i have a problem, in my vuejs project the promise always pending, i put the code in main.js.
Thanks in advance...

**Comment by spurushottam13** [comment]
I think the promise is always pending may be because you may not be initializing the lib correct, you have to initialize the lib in both domains.

in exampleA.com
`const x = new bifrostCors("http://exampleB.com/",false)`

and in exampleB.com
`const x = new bifrostCors("http://exampleA.com/",false)`

I hope this will resolve your issue, if not feel free to raise a query

**Comment by spurushottam13** [comment]
No response from user, hope above solutions worked .
